# Generated by Django 4.2 on 2024-06-25 16:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cashdesk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cashdesk_type', models.CharField(choices=[('cash', 'Liquid'), ('mobile', 'Mobile'), ('bank', 'Bancaire')], max_length=50)),
                ('name', models.CharField(max_length=500)),
                ('phone', models.CharField(blank=True, max_length=500, null=True)),
                ('acc_number', models.CharField(blank=True, max_length=500, null=True)),
                ('debits', models.IntegerField(blank=True, default='0', null=True)),
                ('credits', models.IntegerField(blank=True, default='0', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_featured', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='store/categories/')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('entity_type', models.CharField(choices=[('person', 'Individu'), ('company', 'Compagnie')], default='company', max_length=50)),
                ('sex', models.CharField(choices=[('male', 'Masculin'), ('female', 'Féminin'), ('neutral', 'Neutre')], default='neutral', max_length=50)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.category')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('is_valid', models.BooleanField(default=False)),
                ('initiator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiator', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('brand', models.CharField(default='Générique', max_length=256)),
                ('unit', models.CharField(choices=[('Kg', 'Kilos'), ('L', 'Litres'), ('Ut', 'Unités')], max_length=50)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='store/products/')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.category')),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.family')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit', models.CharField(choices=[('pending', 'En attente'), ('valid', 'Validée'), ('rejected', 'Rejetée')], default='pending', max_length=50)),
                ('payment_option', models.CharField(choices=[('bank', 'Banque'), ('cash', 'Espece'), ('mobil', 'Mobile')], default='cash', max_length=50)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Impayé'), ('partly_paid', 'Payé en partie'), ('paid', 'Payé')], default='unpaid', max_length=50)),
                ('label', models.CharField(blank=True, default='Achat de produit(s)', max_length=200, null=True)),
                ('total', models.IntegerField(default=0)),
                ('discount', models.IntegerField(blank=True, default='0', null=True)),
                ('observation', models.CharField(blank=True, max_length=500, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('cashdesk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.cashdesk')),
            ],
        ),
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot', models.IntegerField(blank=True, default=0, null=True)),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('price', models.IntegerField(blank=True, default=0, null=True)),
                ('promo_price', models.IntegerField(blank=True, default=0, null=True)),
                ('is_promoted', models.BooleanField(default=False)),
                ('observation', models.CharField(blank=True, max_length=500, null=True)),
                ('production_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.product')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit', models.CharField(choices=[('pending', 'En attente'), ('valid', 'Validée'), ('rejected', 'Rejetée')], default='pending', max_length=50)),
                ('items', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('discount', models.IntegerField(blank=True, default='0', null=True)),
                ('observation', models.CharField(blank=True, max_length=500, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('buyer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.client')),
                ('cashdesk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.cashdesk')),
            ],
        ),
        migrations.CreateModel(
            name='StockInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('purchase', 'Achat'), ('return', 'Retour'), ('transfer', 'Transfer'), ('difference', 'Difference d’inventaire'), ('gift', 'Cadeau')], default='purchase', max_length=50)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('initiator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StockOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('sale', 'Vente'), ('usage', 'Utilisation interne'), ('transfer', 'Transfer'), ('difference', 'Difference d’inventaire'), ('gift', 'Don')], default='sale', max_length=50)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('initiator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_type', models.CharField(choices=[('generic', 'Generique'), ('pronap', 'Pronap')], max_length=50)),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('address', models.CharField(default='', max_length=255)),
                ('city', models.CharField(default='', max_length=255)),
                ('country', models.CharField(default='', max_length=255)),
                ('phone', models.CharField(default='', max_length=255)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='store/')),
                ('is_active', models.BooleanField(default=False)),
                ('is_open', models.BooleanField(default=False)),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('opening_date', models.DateField(blank=True, null=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_manager', to=settings.AUTH_USER_MODEL)),
                ('workers', models.ManyToManyField(blank=True, related_name='store_workers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('domain', models.CharField(max_length=255)),
                ('is_new', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('entity_type', models.CharField(choices=[('person', 'Individu'), ('company', 'Compagnie')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('credit', 'Crédit'), ('debit', 'Débit')], max_length=50)),
                ('amount', models.IntegerField(blank=True, default='0', null=True)),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('cashdesk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.cashdesk')),
                ('initiator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.store')),
            ],
        ),
        migrations.CreateModel(
            name='StockOutputItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('product_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.productstock')),
                ('stock_output', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.stockoutput')),
            ],
        ),
        migrations.AddField(
            model_name='stockoutput',
            name='product_stocks',
            field=models.ManyToManyField(through='base.StockOutputItem', to='base.productstock'),
        ),
        migrations.CreateModel(
            name='StockInputItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('product_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.productstock')),
                ('stock_input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.stockinput')),
            ],
        ),
        migrations.AddField(
            model_name='stockinput',
            name='product_stocks',
            field=models.ManyToManyField(through='base.StockInputItem', to='base.productstock'),
        ),
        migrations.CreateModel(
            name='ServicePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit', models.CharField(choices=[('pending', 'En attente'), ('valid', 'Validée'), ('rejected', 'Rejetée')], default='pending', max_length=50)),
                ('payment_option', models.CharField(choices=[('bank', 'Banque'), ('cash', 'Espece'), ('mobil', 'Mobile')], default='cash', max_length=50)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Impayé'), ('partly_paid', 'Payé en partie'), ('paid', 'Payé')], default='unpaid', max_length=50)),
                ('label', models.CharField(blank=True, default='Achat de service(s)', max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('total', models.PositiveIntegerField(default=0)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('cashdesk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.cashdesk')),
                ('store', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.store')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('product_stock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.productstock')),
                ('sale', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.sale')),
            ],
        ),
        migrations.AddField(
            model_name='sale',
            name='product_stocks',
            field=models.ManyToManyField(through='base.SaleItem', to='base.productstock'),
        ),
        migrations.AddField(
            model_name='sale',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sale',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.store'),
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('product_stock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.productstock')),
                ('purchase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.productpurchase')),
            ],
        ),
        migrations.AddField(
            model_name='productstock',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.supplier'),
        ),
        migrations.AddField(
            model_name='productpurchase',
            name='product_stocks',
            field=models.ManyToManyField(through='base.PurchaseItem', to='base.productstock'),
        ),
        migrations.AddField(
            model_name='productpurchase',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.store'),
        ),
        migrations.AddField(
            model_name='productpurchase',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.supplier'),
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.store'),
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_expected', models.PositiveIntegerField(default=0)),
                ('quantity_found', models.PositiveIntegerField(default=0)),
                ('comment', models.CharField(blank=True, max_length=500, null=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.inventory')),
                ('product_stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.productstock')),
            ],
        ),
        migrations.AddField(
            model_name='cashdesk',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.store'),
        ),
    ]
