# Generated by Django 4.2 on 2024-07-01 11:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashdesk',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.store'),
        ),
        migrations.AlterField(
            model_name='product',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.store'),
        ),
        migrations.AlterField(
            model_name='productpurchase',
            name='audit',
            field=models.CharField(choices=[('pending', 'En attente'), ('validated', 'Validé'), ('rejected', 'Rejeté')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='productpurchase',
            name='cashdesk',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.cashdesk'),
        ),
        migrations.AlterField(
            model_name='productpurchase',
            name='payment_option',
            field=models.CharField(choices=[('bank', 'Banque'), ('cash', 'Espèce'), ('mobil', 'Mobile')], default='cash', max_length=50),
        ),
        migrations.AlterField(
            model_name='productpurchase',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Impayé'), ('partly_paid', 'Payé en partie'), ('paid', 'Payé en totalité')], default='unpaid', max_length=50),
        ),
        migrations.AlterField(
            model_name='productpurchase',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productstock',
            name='supplier',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.supplier'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='audit',
            field=models.CharField(choices=[('pending', 'En attente'), ('validated', 'Validé'), ('rejected', 'Rejeté')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='sale',
            name='cashdesk',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.cashdesk'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.store'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicepurchase',
            name='audit',
            field=models.CharField(choices=[('pending', 'En attente'), ('validated', 'Validé'), ('rejected', 'Rejeté')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='servicepurchase',
            name='cashdesk',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.cashdesk'),
        ),
        migrations.AlterField(
            model_name='servicepurchase',
            name='payment_option',
            field=models.CharField(choices=[('bank', 'Banque'), ('cash', 'Espèce'), ('mobil', 'Mobile')], default='cash', max_length=50),
        ),
        migrations.AlterField(
            model_name='servicepurchase',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Impayé'), ('partly_paid', 'Payé en partie'), ('paid', 'Payé en totalité')], default='unpaid', max_length=50),
        ),
        migrations.AlterField(
            model_name='servicepurchase',
            name='supplier',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.supplier'),
        ),
        migrations.AlterField(
            model_name='servicepurchase',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stockoutput',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.store'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
