# Generated by Django 4.2 on 2024-07-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_lot_remove_client_entity_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_type',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='cashdesk',
            name='cashdesk_type',
        ),
        migrations.AddField(
            model_name='cashdesk',
            name='type',
            field=models.CharField(choices=[('cash', 'Physique'), ('mobile', 'Mobile'), ('bank', 'Bancaire')], default='cash', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='audit',
            field=models.CharField(choices=[('pending', 'En attente'), ('validated', 'Validé'), ('rejected', 'Rejeté')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='type',
            field=models.CharField(choices=[('person', 'Personne'), ('company', 'Compagnie')], default='company', max_length=50),
        ),
    ]
