# Generated by Django 4.2 on 2024-07-03 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_transaction_content_type_transaction_object_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productpurchase',
            old_name='discount',
            new_name='amount_paid',
        ),
        migrations.AddField(
            model_name='servicepurchase',
            name='amount_paid',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
