# Generated by Django 4.2 on 2024-07-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_discount_productpurchase_amount_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpurchase',
            name='amount_paid',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='discount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='servicepurchase',
            name='amount_paid',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('credit', 'Encaissement'), ('debit', 'Décaissement')], max_length=50),
        ),
    ]
