# Generated by Django 4.2 on 2024-07-03 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_productpurchase_amount_paid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='store_type',
            new_name='type',
        ),
    ]
