# Generated by Django 4.2 on 2024-07-03 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_rename_store_type_store_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpurchase',
            name='supplier',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.supplier'),
        ),
    ]
