# Generated by Django 4.2 on 2024-07-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_productpurchase_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashdesk',
            name='carrier',
            field=models.CharField(choices=[('moov', 'Moov Africa'), ('togocom', 'Togocom')], default='moov', max_length=50),
            preserve_default=False,
        ),
    ]
