# Generated by Django 4.2 on 2024-07-04 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_cashdesk_carrier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashdesk',
            name='carrier',
            field=models.CharField(blank=True, choices=[('moov', 'Moov Africa'), ('togocom', 'Togocom')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cashdesk',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.store'),
        ),
    ]
