# Generated by Django 4.2 on 2024-07-05 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_cashdesk_carrier_alter_cashdesk_store'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='buyer',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='seller',
            new_name='initiator',
        ),
    ]
