# Generated by Django 4.2 on 2024-07-05 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_rename_buyer_sale_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockinput',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.store'),
        ),
        migrations.AddField(
            model_name='stockoutput',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.store'),
        ),
    ]
