# Generated by Django 4.2 on 2024-07-08 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_debt_due_date_alter_receivable_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receivable',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
