# Generated by Django 4.2 on 2024-07-08 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_entitytype_cashdesk_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashdesk',
            name='balance',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cashdesk',
            name='credits',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cashdesk',
            name='debits',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
