# Generated by Django 4.2 on 2024-07-08 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_alter_cashdesk_balance_alter_cashdesk_credits_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productpurchase',
            old_name='observation',
            new_name='description',
        ),
    ]
