# Generated by Django 4.2 on 2024-07-09 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_remove_client_type_remove_supplier_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.entitytype'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.entitytype'),
        ),
    ]
