# Generated by Django 4.2 on 2024-07-09 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0028_client_type_supplier_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashdeskClosing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_expected', models.PositiveIntegerField(default=0)),
                ('balance_found', models.PositiveIntegerField(default=0)),
                ('difference', models.IntegerField(default=0)),
                ('comment', models.CharField(blank=True, max_length=500, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('cashdesk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.cashdesk')),
                ('initiator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashdesk_initiator', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashdesk_supervisor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CashdeskClosingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=0)),
                ('amount', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CashReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('notes', 'Billets'), ('coins', 'Pièces')], max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='date',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='is_valid',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='store',
        ),
        migrations.RemoveField(
            model_name='lot',
            name='date',
        ),
        migrations.RemoveField(
            model_name='productstock',
            name='lot',
        ),
        migrations.AddField(
            model_name='inventory',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='difference',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventory',
            name='product_stock',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.productstock'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='quantity_expected',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventory',
            name='quantity_found',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lot',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.store'),
        ),
        migrations.AddField(
            model_name='lot',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockinput',
            name='items',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stockinput',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stockoutput',
            name='items',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stockoutput',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='initiator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_initiator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_supervisor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='InventoryItem',
        ),
        migrations.AddField(
            model_name='cashdeskclosingitem',
            name='cash_receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.cashreceipt'),
        ),
        migrations.AddField(
            model_name='cashdeskclosingitem',
            name='cashdesk_closing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.cashdeskclosing'),
        ),
    ]
