# Generated by Django 4.2 on 2024-07-09 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_rename_cashdeskclosingitem_deskclosingitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashdeskclosing',
            name='balance_expected',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cashdeskclosing',
            name='balance_found',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
