# Generated by Django 4.2 on 2024-07-10 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_alter_cashdeskclosing_balance_expected_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashdeskclosing',
            name='balance_expected',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cashdeskclosing',
            name='balance_found',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
