# Generated by Django 4.2 on 2024-07-10 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_alter_cashdeskclosing_balance_expected_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_expected', models.PositiveIntegerField(default=0)),
                ('quantity_found', models.PositiveIntegerField(default=0)),
                ('difference', models.IntegerField(default=0)),
                ('comment', models.CharField(blank=True, max_length=500, null=True)),
                ('product_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.productstock')),
            ],
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
