# Generated by Django 4.2 on 2024-07-11 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_inventory_inventoryitem_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosingCashReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
                ('total_amount', models.PositiveIntegerField(default=0)),
                ('cash_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.cashreceipt')),
                ('cashdesk_closing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.cashdeskclosing')),
            ],
        ),
    ]
