# Generated by Django 4.2 on 2024-07-11 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_closingcashreceipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='closingcashreceipt',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
