# Generated by Django 4.2 on 2024-07-11 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_closingcashreceipt_timestamp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeskClosingItem',
        ),
    ]
