# Generated by Django 4.2 on 2024-07-12 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_delete_deskclosingitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashdeskclosing',
            name='balance_expected',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cashdeskclosing',
            name='balance_found',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cashdeskclosing',
            name='difference',
            field=models.BigIntegerField(default=0),
        ),
    ]
