# Generated by Django 4.2 on 2024-07-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_alter_cashdeskclosing_balance_expected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='total_paid',
            field=models.IntegerField(default=0),
        ),
    ]
