# Generated by Django 4.2 on 2024-07-14 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_sale_total_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='cashdesk',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='description',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='initiator',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='store',
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.payment'),
        ),
    ]
