# Generated by Django 4.2 on 2024-07-15 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0042_remove_receivable_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productpurchase',
            old_name='amount_paid',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='servicepurchase',
            old_name='amount_paid',
            new_name='amount',
        ),
    ]
