# Generated by Django 4.2 on 2024-07-16 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0044_productpurchase_initiator_servicepurchase_initiator'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='is_fully_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productstock',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.lot'),
        ),
        migrations.AddField(
            model_name='receivable',
            name='is_fully_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cashdesk',
            name='credits',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cashdesk',
            name='debits',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.PositiveIntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.PositiveIntegerField(blank=True, default='0', null=True),
        ),
    ]
