# Generated by Django 4.2 on 2024-07-17 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0046_stockoperation_stockoperationitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('product', 'Produit'), ('service', 'Service')], default='product', max_length=10)),
                ('audit', models.CharField(choices=[('pending', 'En attente'), ('validated', 'Validé'), ('rejected', 'Rejeté')], default='pending', max_length=50)),
                ('payment_option', models.CharField(choices=[('bank', 'Banque'), ('cash', 'Espèce'), ('mobil', 'Mobile')], default='cash', max_length=50)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Impayé'), ('partly_paid', 'Payé en partie'), ('paid', 'Payé en totalité')], default='unpaid', max_length=50)),
                ('label', models.CharField(blank=True, default='Achat', max_length=200, null=True)),
                ('total', models.IntegerField(default=0)),
                ('amount', models.IntegerField(blank=True, default=0, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('cashdesk', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.cashdesk')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.store')),
                ('supplier', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.supplier')),
            ],
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='product_stock',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='purchase',
        ),
        migrations.RemoveField(
            model_name='servicepurchase',
            name='cashdesk',
        ),
        migrations.RemoveField(
            model_name='servicepurchase',
            name='initiator',
        ),
        migrations.RemoveField(
            model_name='servicepurchase',
            name='store',
        ),
        migrations.RemoveField(
            model_name='servicepurchase',
            name='supplier',
        ),
        migrations.AlterField(
            model_name='stockoperation',
            name='subtype',
            field=models.CharField(choices=[('purchase', 'Achat'), ('return', 'Retour'), ('transfer', 'Transfer'), ('difference', 'Difference d’inventaire'), ('gift', 'Cadeau/Don'), ('sale', 'Vente'), ('usage', 'Utilisation interne')], max_length=50),
        ),
        migrations.DeleteModel(
            name='ProductPurchase',
        ),
        migrations.DeleteModel(
            name='PurchaseItem',
        ),
        migrations.DeleteModel(
            name='ServicePurchase',
        ),
    ]
