# Generated by Django 4.2 on 2024-07-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0052_remove_transaction_payment_transaction_cashdesk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='type',
            field=models.CharField(choices=[('product', 'Produit'), ('service', 'Service'), ('tax', 'Impot'), ('community', 'Municipal')], default='product', max_length=10),
        ),
    ]
