# Generated by Django 4.2 on 2024-07-20 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0056_alter_cashdeskclosing_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debt',
            name='is_fully_paid',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='is_fully_paid',
        ),
        migrations.RemoveField(
            model_name='receivable',
            name='is_fully_paid',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='is_fully_paid',
        ),
    ]
