# Generated by Django 4.2 on 2024-07-20 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0057_remove_debt_is_fully_paid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='amount',
        ),
        migrations.AddField(
            model_name='debt',
            name='is_fully_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchase',
            name='total_paid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='receivable',
            name='is_fully_paid',
            field=models.BooleanField(default=False),
        ),
    ]
