# Generated by Django 4.2 on 2024-07-21 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0059_debt_purchase_alter_productstock_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstock',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
