# Generated by Django 4.2 on 2024-07-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0062_product_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='abbreviation',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, null=True),
        ),
    ]
