from django.urls import path, register_converter
from .views import *
from utils import HashIdConverter

register_converter(HashIdConverter, "hashid")

urlpatterns = [
    path('', home, name='home'),
    path('stores/', stores, name='stores'),
    path('stores/list/', stores_list, name='stores_list'),
    path('stores/create/', create_store, name='create_store'),
    path('stores/<hashid:pk>/', store_details, name='store_details'),
    path('stores/<hashid:pk>/edit/', edit_store, name='edit_store'),
    path('stores/<hashid:pk>/transactions/',
         store_transactions, name='store_transactions'),
    path('stores/<hashid:pk>/stock/', store_stock, name='store_stock'),
    # ----------------------------------------------------------------------------
    path('products/', products, name='products'),
    path('products/stocks/', product_stocks, name='product_stocks'),
    path('products/create/', create_product, name='create_product'),
    path('products/list/', products_list, name='products_list'),
    path('products/grid/', products_grid, name='products_grid'),
    path('products/filter/', filter_products, name='filter_products'),
    path('products/<hashid:pk>/', product_details, name='product_details'),
    path('products/<hashid:pk>/edit/', edit_product, name='edit_product'),
    # ----------------------------------------------------------------------------
    path('entities/types/list/', entity_types_list, name='entity_types_list'),
    path('entities/types/createv', create_entity_type, name='create_entity_type'),
    path('entities/types/<hashid:pk>/edit/', edit_entity_type, name='edit_entity_type'),
    # ----------------------------------------------------------------------------
    path('stock/', stock, name='stock'),
    # ----------------
    path('stock/overview/', stock_overview, name='stock_overview'),
    path('stock/inventories/', inventories, name='inventories'),
    path('stock/inventories/create', create_inventory, name='create_inventory'),
    path('stock/inventories/<hashid:pk>/', inventory_details, name='inventory_details'),
    path('stock/inventories/<hashid:pk>/edit/', edit_inventory, name='edit_inventory'),
    # ----------------
    path('stock/products/list/', prod_stock_list, name='prod_stock_list'),
    path('stock/products/create/', create_prod_stock, name='create_prod_stock'),
    path('stock/products/filter/', filter_prod_stock, name='filter_prod_stock'),
    path('stock/products/<hashid:pk>/',
         prod_stock_details, name='prod_stock_details'),
    path('stock/products/<hashid:pk>/edit/',
         edit_prod_stock, name='edit_prod_stock'),
    path('stock/products/<hashid:pk>/stocks/', prod_stocks, name='prod_stocks'),
    # ------------------------------
    path('stock/ops/create/<str:pk>/', create_stock_ops,
         name='create_stock_ops'),
    path('stock/ops/<str:pk>/', stock_ops, name='stock_ops'),
    path('stock/ops/<hashid:pk>/details/', stock_ops_details, name='stock_ops_details'),
    path('stock/ops/<hashid:pk>/edit/',
         edit_stock_ops, name='edit_stock_ops'),
    # ----------------
    path('stock/ops/<hashid:pk>/info/',
         stock_ops_info, name='stock_ops_info'),
    path('stock/ops/<hashid:pk>/items/',
         stock_ops_items, name='stock_ops_items'),
    path('stock/ops/<hashid:pk>/create/item/',
         create_stock_ops_item, name='create_stock_ops_item'),
    path('stock/ops/<hashid:pk>/edit/item/',
         edit_stock_ops_item, name='edit_stock_ops_item'),
    # ----------------------------------------------------------------------------
    path('cart/', cart, name='cart'),
    path('sales/', sales, name='sales'),
    path('sales/pos/', sale_point, name='sale_point'),
    path('sales/pos/add_item/', add_to_cart, name='add_to_cart'),
    path('sales/pos/remove_item/', remove_from_cart, name='remove_from_cart'),
    path('sales/pos/clear_item/', clear_item, name='clear_item'),
    path('sales/pos/clear_cart/', clear_cart, name='clear_cart'),
    path('sales/pos/checkout/', checkout, name='checkout'),
    # ----------------------------------------------------------------------------
    path('sales/create/', create_sale, name='create_sale'),
    path('sales/<hashid:pk>/', sale_details, name='sale_details'),
    path('sales/<hashid:pk>/edit/', edit_sale, name='edit_sale'),
    path('sales/<hashid:pk>/info/', sale_info, name='sale_info'),
    path('sales/<hashid:pk>/items/list/', sale_items, name='sale_items'),
    path('sales/<hashid:pk>/items/create/',
         create_sale_item, name='create_sale_item'),
    path('sales/items/<hashid:pk>/edit/',
         edit_sale_item, name='edit_sale_item'),
    path('sales/<hashid:pk>/payments/create/',
         create_sale_payment, name='create_sale_payment'),
    # ----------------------------------------------------------------------------
    path('purchases/', purchases, name='purchases'),
    path('purchases/create/<str:pk>/', create_purchase, name='create_purchase'),
    path('purchases/list/<str:pk>/', purchases_list, name='purchases_list'),
    path('purchases/<hashid:pk>/edit/', edit_purchase, name='edit_purchase'),
    path('purchases/<hashid:pk>/info/', purchase_info, name='purchase_info'),
    # --------------------------
    path('purchases/items/<hashid:pk>/list/',
         purchase_items, name='purchase_items'),
    path('purchases/items/<hashid:pk>/create/',
         create_purchase_item, name='create_purchase_item'),
    path('purchases/items/<hashid:pk>/edit/',
         edit_purchase_item, name='edit_purchase_item'),
    # --------------------------
    path('purchases/<hashid:pk>/create/payment/',
         create_purchase_payment, name='create_purchase_payment'),
    path('purchases/<hashid:pk>/',
         purchase_details, name='purchase_details'),
    # ----------------------------------------------------------------------------
    path('clients/', clients, name='clients'),
    path('clients/create/', create_client, name='create_client'),
    path('clients/list/', clients_list, name='clients_list'),
    path('clients/filter/', filter_clients, name='filter_clients'),
    path('clients/<hashid:pk>/', client_details, name='client_details'),
    path('clients/<hashid:pk>/edit/', edit_client, name='edit_client'),
    path('clients/<hashid:pk>/purchases/',
         client_purchases, name='client_purchases'),
    path('clients/<hashid:pk>/purchases/filter/',
         filter_client_purchases, name='filter_client_purchases'),
    # ----------------------------------------------------------------------------
    path('suppliers/', suppliers, name='suppliers'),
    path('suppliers/create/', create_supplier, name='create_supplier'),
    path('suppliers/list/', suppliers_list, name='suppliers_list'),
    path('suppliers/filter/', filter_suppliers, name='filter_suppliers'),
    path('suppliers/<hashid:pk>/', supplier_details, name='supplier_details'),
    path('suppliers/<hashid:pk>/edit/', edit_supplier, name='edit_supplier'),
    # ----------------------------------------------------------------------------
    path('parameters/', parameters, name='parameters'),
    path('categories/list/', categories_list, name='categories_list'),
    path('categories/add/', create_category, name='create_category'),
    path('categories/<hashid:pk>/edit/', edit_category, name='edit_category'),
    # --------------------------
    path('families/load/', load_families, name='load_families'),
    path('families/list/', families_list, name='families_list'),
    path('families/add/', create_family, name='create_family'),
    path('families/<hashid:pk>/edit/',
         edit_family, name='edit_family'),
    # --------------------------
    path('finances/', finances, name='finances'),
    path('finances/reports/', reports, name='reports'),
    path('finances/treasury/', treasury, name='treasury'),
    # --------------------------
    path('finances/cashdesks/create/', create_cashdesk, name='create_cashdesk'),
    path('finances/cashdesks/list/', cashdesks_list, name='cashdesks_list'),
    path('finances/cashdesks/<hashid:pk>/',
         cashdesk_details, name='cashdesk_details'),
    path('finances/cashdesks/<hashid:pk>/edit/',
         edit_cashdesk, name='edit_cashdesk'),
    # --------------------------
    path('finances/cashdesks/transactions/<hashid:pk>/',
         desk_transactions, name='desk_transactions'),
    # --------------------------
    path('finances/cashdesks/desk_closings/list/<hashid:pk>/',
         desk_closings_list, name='desk_closings_list'),
    path('finances/cashdesks/desk_closings/details/<hashid:pk>/',
         desk_closing_details, name='desk_closing_details'),
    path('finances/cashdesks/desk_closings/<hashid:pk>/',
         create_closing_receipt, name='create_closing_receipt'),
    path('finances/cashdesks/desk_closings/<hashid:pk>/create/',
         create_desk_closing, name='create_desk_closing'),
    path('finances/cashdesks/desk_closings/<hashid:pk>/edit/',
         edit_desk_closing, name='edit_desk_closing'),
    path('finances/cashdesks/desk_closings/<hashid:pk>/correct/',
         correct_desk_closing, name='correct_desk_closing'),
    # --------------------------
    path('finances/credits/list/', credits_list, name='credits_list'),
    path('finances/credits/create/', create_credit, name='create_credit'),
    path('finances/debits/list/', debits_list, name='debits_list'),
    path('finances/debits/create/', create_debit, name='create_debit'),
    # --------------------------
    path('finances/receivables/list/', receivables_list, name='receivables_list'),
    path('finances/receivables/create/',
         create_receivable, name='create_receivable'),
    path('finances/receivables/store/<hashid:pk>/',
         store_receivables, name='store_receivables'),
    path('finances/receivables/<hashid:pk>/',
         receivable_details, name='receivable_details'),
    path('finances/receivables/<hashid:pk>/edit/',
         edit_receivable, name='edit_receivable'),
    # --------------------------
    path('finances/debts/list/', debts_list, name='debts_list'),
    path('finances/debts/create/', create_debt, name='create_debt'),
    path('finances/debts/<hashid:pk>/', debt_details, name='debt_details'),
    path('finances/debts/store/<hashid:pk>/', store_debts, name='store_debts'),
    path('finances/debts/<hashid:pk>/edit/', edit_debt, name='edit_debt'),
    # --------------------------
    path('finances/transactions/list/',
         transactions_list, name='transactions_list'),
    path('finances/transactions/filter/',
         filter_transactions, name='filter_transactions'),
    path('finances/transactions/<hashid:pk>/',
         transaction_details, name='transaction_details'),
    path('finances/transactions/<hashid:pk>/edit/',
         edit_transaction, name='edit_transaction'),
    path('finances/transactions/create/<hashid:pk>/',
         create_transaction, name='create_transaction'),
    # --------------------------
    path('finances/payments/create/', create_payment, name='create_payment'),
    path('finances/payments/list/', payments_list, name='payments_list'),
    path('finances/payments/store/<hashid:pk>/', store_payments, name='store_payments'),
    path('finances/payments/<hashid:pk>/',
         payment_details, name='payment_details'),
    path('finances/payments/<hashid:pk>/edit/',
         edit_payment, name='edit_payment'),
    # --------------------------
    path('base/objects/<hashid:pk>/<str:model_name>/delete/',
         delete_base_object, name='delete_base_object'),
]
